// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHuK-yEJLSSQnldNbfIH2IEIu8a7YPISI',
    appId: '1:887082651562:web:e134ff36122f016899e5d3',
    messagingSenderId: '887082651562',
    projectId: 'baidaa',
    authDomain: 'baidaa.firebaseapp.com',
    storageBucket: 'baidaa.appspot.com',
    measurementId: 'G-41NN5BK5ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfhfT0NSRuDlOwuKVmyCDnyE3_IrXxK5I',
    appId: '1:887082651562:android:ea1d43a1b094282299e5d3',
    messagingSenderId: '887082651562',
    projectId: 'baidaa',
    storageBucket: 'baidaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6tEqkeO_X9nSsQ1iRlinVoX_gZWlzbC8',
    appId: '1:887082651562:ios:7388d7c8875caf3399e5d3',
    messagingSenderId: '887082651562',
    projectId: 'baidaa',
    storageBucket: 'baidaa.appspot.com',
    iosClientId: '887082651562-rolmvep2hneudsusc2u1ki2ghtn7q8ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6tEqkeO_X9nSsQ1iRlinVoX_gZWlzbC8',
    appId: '1:887082651562:ios:9cf184aa74d61cf299e5d3',
    messagingSenderId: '887082651562',
    projectId: 'baidaa',
    storageBucket: 'baidaa.appspot.com',
    iosClientId: '887082651562-rdrsq02p8i58rh7534gnojjsbo4pl1kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskone.RunnerTests',
  );
}
